# Generated by Django 3.0 on 2020-06-19 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imag', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('size_type', models.IntegerField(choices=[(1, '600x600'), (2, '700x700'), (3, '800x800'), (4, '900x900'), (5, '1000x1000')], default='1', verbose_name='Выберите размер для ресайза изображения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
